//! Generates two versions of a fake closed-source chat application, built
//! with the test-suite ELF writer, for trying `elfcaps scan` and `elfcaps diff`
//! without real proprietary binaries:
//!
//!     cargo run --example make_bundle -- demo
//!
//! writes `demo/chatapp-1.0` and `demo/chatapp-1.1`.

#[path = "../tests/support/writer.rs"]
mod writer;

use std::fs;
use std::path::Path;
use writer::ElfSpec;

fn write(root: &Path, rel: &str, spec: ElfSpec) -> std::io::Result<()> {
    let path = root.join(rel);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, spec.build())
}

fn bundle(root: &Path, newer: bool) -> std::io::Result<()> {
    if root.exists() {
        fs::remove_dir_all(root)?;
    }
    write(
        root,
        "bin/chatapp",
        ElfSpec::exe()
            .runpath("$ORIGIN/../lib")
            .needed("libchatcore.so")
            .needed("libQt5Gui.so.5")
            .needed("libc.so.6")
            .import_versioned("printf", "libc.so.6", "GLIBC_2.2.5")
            .import("_ZN12QApplication4execEv"),
    )?;
    write(
        root,
        "lib/libchatcore.so",
        ElfSpec::lib("libchatcore.so")
            .runpath("$ORIGIN")
            .needed("libQt5Network.so.5")
            .needed("libupdater.so")
            .import("_ZN21QNetworkAccessManager3getERK15QNetworkRequest")
            .export("chat_core_init"),
    )?;
    write(
        root,
        "lib/libQt5Gui.so.5",
        ElfSpec::lib("libQt5Gui.so.5")
            .runpath("$ORIGIN")
            .needed("libQt5XcbQpa.so.5")
            .export("_ZN15QGuiApplication4execEv"),
    )?;
    let mut qpa = ElfSpec::lib("libQt5XcbQpa.so.5")
        .needed("libxcb.so.1")
        .needed("libxcb-xfixes.so.0")
        .import_versioned("xcb_convert_selection", "libxcb.so.1", "XCB_1.0")
        .import("xcb_xfixes_select_selection_notify")
        .import("xcb_get_image")
        .import("xcb_query_tree");
    if newer {
        qpa = qpa.import("xcb_grab_keyboard");
    }
    write(root, "lib/libQt5XcbQpa.so.5", qpa)?;
    write(
        root,
        "lib/libQt5Network.so.5",
        ElfSpec::lib("libQt5Network.so.5"),
    )?;

    let mut updater = ElfSpec::lib("libupdater.so")
        .needed("libdl.so.2")
        .import("dlopen")
        .import("dlsym")
        .rodata("libXtst.so.6")
        .rodata("https://updates.example.invalid/check");
    if newer {
        updater = updater
            .rodata("XRecordEnableContext")
            .rodata("org.freedesktop.portal.ScreenCast");
    }
    write(root, "lib/libupdater.so", updater)?;

    write(
        root,
        "lib/plugins/libscreenshare.so",
        ElfSpec::lib("libscreenshare.so")
            .runpath("$ORIGIN/..")
            .needed("libQt5XcbQpa.so.5")
            .needed("libXext.so.6")
            .import("XShmGetImage")
            .import("XDamageCreate"),
    )?;
    fs::write(
        root.join("README.txt"),
        "Demo bundle generated by elfcaps\n",
    )
}

fn main() {
    let out = std::env::args()
        .nth(1)
        .unwrap_or_else(|| "demo".to_string());
    let out = Path::new(&out);
    for (name, newer) in [("chatapp-1.0", false), ("chatapp-1.1", true)] {
        let root = out.join(name);
        if let Err(e) = bundle(&root, newer) {
            eprintln!("make_bundle: {}: {e}", root.display());
            std::process::exit(1);
        }
        println!("wrote {}", root.display());
    }
}
